### PR TITLE
fix some links and add HaGeZi - Multi LIGHT

### PR DESCRIPTION
**Pull request by bestplayerbot**

### CODE REVIEW

**Review by yokoffing — CHANGES_REQUESTED** [review]
The emoji's as text, e.g. `:bookmark:`, are intentional. This is to preserve compatibility with other sites, browsers, OS, etc.

**Comment by bestplayerbotphone** [comment]
@norilana I think you should since it's not listed in the blocklists section

**Comment by yokoffing** [comment]
> @norilana Do I need to remove the nextdns default filter?

**NextDNS Ads & Trackers Blocklist** is not recommended.

**Comment by yokoffing** [comment]
@norilana https://github.com/yokoffing/NextDNS-Config#blocklists-1:~:text=You%20may%20wonder%20why

**Pull request merged**
