### PR TITLE
Fix some broken links

### PR DESCRIPTION
**Pull request by iam-py-test**
https://github.com/nextdns/metadata has removed all their lists, and moved everything either to other repos or are now 
"internal"
I fixed a few links and removed a few which no longer exist in any form, but there are a few I wasn't sure about so just left untouched.
Thanks

### CODE REVIEW

**Comment by yokoffing** [comment]
Apologies, I'm just now seeing this. I'm not receiving notifications for this repo, and I still need to locate the setting responsible for this.

Thank you for the updates😄. It's been on my to-do list, but I haven't gotten around to it.

I'll take a look today and check the ones you haven't edited.

**Comment by yokoffing** [comment]
https://github.com/nextdns/metadata

**Comment by yokoffing** [comment]
@iam-py-test Fixed the notification issue!

Web capture_16-2-2023_134842_github com

**Comment by iam-py-test** [comment]
<details>
<summary>Off topic</summary>
GitHub claims I already have something set, so probably it's something else wrong with my account's notification settings. I remember I turned a lot off so I stopped getting emails for every single automatic commit & new issue in uAssets. I did find one that let me configure if I get notified about repos I'm watching which was disabled, so hopefully enabling that fixed it.
</details>

**Comment by yokoffing** [comment]
> I did find one that let me configure if I get notified about repos I'm watching which was disabled, so hopefully enabling that fixed it.

You mean @ https://github.com/settings/notifications? If so, I can definitely see why you weren't getting notified!

**Comment by yokoffing** [comment]
For future readers: Most of the old links are now [internalized](https://github.com/nextdns/metadata). I've provided archived links in their place. I would've preferred they remained open --- there were many entries missing which were found by various users and in notable lists like Hagezi's --- but this is where we are for now.

**Pull request merged**
