### PR TITLE
hagezi lists

### PR DESCRIPTION
**Pull request by yokoffing**
Waiting on https://github.com/nextdns/blocklists/pull/65

### CODE REVIEW

**Comment by hagezi** [comment]
But you are optimistic. ;)

**Comment by hagezi** [comment]
@yokoffing My understanding of strict and agressive is the other way around, so, aggressive is the Pro Plus, strict is the Ultimate?
Is strict not more than aggressive?

**Comment by yokoffing** [comment]
> @bestplayerbot Shouldn't 1Hosts (Lite), oisd and 1Hosts (Pro) be removed from optional because they are already included

Technically yes; however, they're good lists, and I've developed good rapport with those maintainers. Maybe I'll rename that section as "Alternate Setup" or something.

> @hagezi Is strict not "more" than aggressive? My understanding of strict and aggressive is the other way around

I'm using the definitions set forth [here](https://github.com/yokoffing/NextDNS-Config#blocklists-1). It boils down to semantics. Regardless of the word, the definitions and the layout (severity ranges from minimal to severe) are there.

> In Germany, that's the way it is.

I wasn't aware of that! I asked someone who speaks Spanish and they said my definitions match the English understanding of these words.

I'm not putting too much thought into it until I see NextDNS make changes to their blocklists.

**Comment by yokoffing** [comment]
> is that going to still be too aggressive since it includes 1Host Lite

Yes. What I have corresponds to the definitions in the guide. But feel free to try out Hagezi LIGHT and let me know how it goes in a few weeks.

**Comment by travisboss** [comment]
> Yes. What I have corresponds to the definitions in the guide. But feel free to try out Hagezi LIGHT for a few weeks and let me know how it goes.

Testing now.

**Pull request merged**
