### PR TITLE
emojis

### PR DESCRIPTION
**Pull request by bestplayerbotphone**

### CODE REVIEW

**Comment by bestplayerbotphone** [comment]
don't merge yet

**Comment by yokoffing** [comment]
Thank you. Shame that GitHub doesn't allow for easier reversing of mergers in pull requests.

**Comment by bestplayerbotphone** [comment]
this pr may be merged now

**Comment by yokoffing** [comment]
> maybe 1Hosts (Xtra) should be removed? there are too much false positives

@bestplayerbot I'm not opposed to removing 1Host (Xtra). I just haven't decided on how to reword the description for Aggressive.

Currently, we have:

- **Aggressive:** excessive breakage; many false positives; use on a separate profile to [lockdown single-purpose devices](https://old.reddit.com/r/nextdns/comments/uqap3n/comment/i8q8alf/?context=3)

The current definition doesn't really apply to Hagezi Ultimate, only to 1Host Xtra.

We could use similar language as Hagezi and say,

- **Aggressive:** frequent breakage; should only be used by experienced users

**Comment by hagezi** [comment]
"_Aggressive: frequent breakage; should only be used by experienced users_" fits best in my opinion.

**Comment by hagezi** [comment]
As for 1Host extra, it contains a lot of false positive domains, but it seems that there are users who use such lists - even if the sense behind it is not clear to me. Therefore I would not remove them.

**Comment by yokoffing** [comment]
Moving discussion to #27

**Pull request merged**
